export default [
    {
        id: '1',
        price: 2000,
        year: 2012,
        milliage: 206455,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'All Wheel Drive'
    },
    {
        id: '2',
        price: 3000,
        year: 2012,
        milliage: 200555,
        manufacturer: 'AUDI',
        model: 'ROAD',
        transmission: 'Semi-automatic',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'Front-Wheel Drive'
    },
    {
        id: '3',
        price: 4000,
        year: 2015,
        milliage: 20055,
        manufacturer: 'AUDI',
        model: 'ROAD',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'Rear-Wheel Drive'
    },
    {
        id: '4',
        price: 5000,
        year: 2012,
        milliage: 20650,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'Unknown'
    },
    {
        id: '5',
        price: 6000,
        year: 2012,
        milliage: 2044455,
        manufacturer: 'AUDI',
        model: 'ROAD',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'Rear-Wheel Drive'
    },
    {
        id: '6',
        price: 7000,
        year: 2012,
        milliage: 208455,
        manufacturer: 'AUDI',
        model: 'ROAD',
        transmission: 'Semi-automatic',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'Rear-Wheel Drive'
    },
    {
        id: '7',
        price: 8000,
        year: 2010,
        milliage: 206555,
        manufacturer: 'FORD',
        model: 'Avant',
        transmission: 'Automatic transmission',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'Unknown'
    },
    {
        id: '8',
        price: 9000,
        year: 2012,
        milliage: 106555,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'Unknown'
    },
    {
        id: '9',
        price: 2000,
        year: 2012,
        milliage: 506555,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gas',
        type: 'avto',
        drivertrain: 'Unknown'
    },
    {
        id: '10',
        price: 8000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'Unknown'
    },
    {
        id: '11',
        price: 2500,
        year: 2018,
        milliage: 206555,
        manufacturer: 'BMW',
        model: 'x5',
        transmission: 'Manual gearbox',
        fuel_type: 'Gas',
        type: 'avto',
        drivertrain: 'All Wheel Drive'
    },
    {
        id: '12',
        price: 45000,
        year: 2012,
        milliage: 2065155,
        manufacturer: 'BMW',
        model: 'x6',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'All Wheel Drive'
    },
    {
        id: '13',
        price: 65000,
        year: 2012,
        milliage: 406555,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'All Wheel Drive'
    },
    {
        id: '14',
        price: 25000,
        year: 2015,
        milliage: 206555,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Hybrid',
        type: 'avto',
        drivertrain: 'All Wheel Drive'
    },
    {
        id: '15',
        price: 12000,
        year: 2012,
        milliage: 5555,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gas',
        type: 'avto',
        drivertrain: 'All Wheel Drive'
    },
    {
        id: '16',
        price: 56000,
        year: 2012,
        milliage: 3555,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'All Wheel Drive'
    },
    {
        id: '17',
        price: 52000,
        year: 2016,
        milliage: 2333555,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Hybrid',
        type: 'avto',
        drivertrain: 'All Wheel Drive'
    },
    {
        id: '18',
        price: 96000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'All Wheel Drive'
    },
    {
        id: '19',
        price: 65000,
        year: 2014,
        milliage: 204555,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline',
        type: 'avto',
        drivertrain: 'All Wheel Drive'
    },
    {
        id: '20',
        price: 42000,
        year: 2012,
        milliage: 25555,
        manufacturer: 'AUDI',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Hybrid',
        type: 'avto',
        drivertrain: 'All Wheel Drive'
    },

]