export default [
    {
        id: '1',
        title: 'Car 1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '2',
        title: 'Car 2',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '3',
        title: 'Car 3',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '4',
        title: 'Car 4',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '5',
        title: 'Car 5',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '6',
        title: 'Car 6',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '7',
        title: 'Car 7',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '8',
        title: 'Car 8',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '9',
        title: 'Car 9',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '10',
        title: 'Car 10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '11',
        title: 'Car 11',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '12',
        title: 'Car 12',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '13',
        title: 'Car 13',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '14',
        title: 'Car 14',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '15',
        title: 'Car 15',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '16',
        title: 'Car 16',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '17',
        title: 'Car 17',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '18',
        title: 'Car 18',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '19',
        title: 'Car 19',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },
    {
        id: '20',
        title: 'Car 20',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 2000,
        year: 2012,
        milliage: 206555,
        manufacturer: 'Audi',
        model: 'Avant',
        transmission: 'Manual gearbox',
        fuel_type: 'Gasoline'
    },

]